
spring.application.name=Devolucao-Service

spring.datasource.url=jdbc:postgresql://localhost:5432/Devolucao
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.datadog.metrics.export.apiKey =
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


spring.kafka.consumer.group-id=devolucao-service-group-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type= Service.Devolucao.DTO.TransacaoRealizadaDTO

spring.kafka.consumer.properties.spring.json.value.type.mappings=Service.Transacao_Service.DTO.TransacaoEvento:Service.Devolucao.DTO.TransacaoRealizadaDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=Service.Devolucao.DTO
spring.kafka.consumer.properties.spring.json.use.type.headers=false

logging.level.org.springframework.kafka=INFO
logging.level.comconsumerNotificacao=DEBUG

server.port=8082

