spring.application.name=Tansacao-Service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Transacao
spring.datasource.username=
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.datadog.metrics.export.apiKey =
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
